config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker.js" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "starts#show"

  resource :start, only: [ :show, :new, :create ]
  resource :session, only: [ :new, :create, :destroy ]
  resource :registration, only: [ :new, :create ]
  resources :password_resets, only: [ :new, :create ]
  resources :password_resets, param: :token, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]
  resource :settings, only: [ :show ]
  resources :characters do
    post "activate", on: :member
  end

  # Add stats
  post "add_strength", to: "add_stats#strength"
  post "add_agility", to: "add_stats#agility"
  post "add_vitality", to: "add_stats#vitality"
  post "add_energy", to: "add_stats#energy"

  # Adventure (walk without teleport)
  resource :adventure, only: [ :show ] do
    post "travel"
  end

  resources :hunting, only: [ :index, :show ]
  resource :combat, only: [ :new, :create, :show ]
end

app/controllers/hunting_controller.rb
class HuntingController < ApplicationController
  def index
    @spots = Current.character.map.locations.spots
  end

  def show
    @spot = Current.character.map.locations.spots.find(params[:id])
    return redirect_to hunting_path, alert: "Invalid spot" unless @spot

    @monster = @spot.monsters.order("RANDOM()").first
  end
end

app/views/hunting/index.html.erb
<article>
  <h1>Spots with monsters</h1>
  <ul class="menu">
    <% @spots.each do |spot| %>
      <li class="menu-item">
        <%= link_to spot.name, hunting_path(spot) %>
      </li>
    <% end %>
  </ul>
</article>

app/views/hunting/show.html.erb
<article>
  <% if @monster.present? %>
    <section style="display: flex; flex-direction: column; justify-content: center; align-items: center;">
      <h2>Hunting</h2>

      <table class="quick-combat">
        <tr>
          <td><%= Current.character.name %>[<%= Current.character.level %>]</td>
          <td>versus</td>
          <td><%= @monster.name %>[<%= @monster.level %>]</td>
        </tr>
        <!-- Avatars -->
        <tr>
          <td>
            <div class="avatar player-avatar"></div>
          </td>
          <td></td>
          <td>
            <div class="avatar enemy-avatar"></div
          </td>
        </tr>
        <!-- Attack rate -->
        <tr>
          <td><%= Current.character.attack_rate %></td>
          <td><p title="Attack Rate (Accuracy)">ACC</p></td>
          <td><%= @monster.attack_rate %></td>
        </tr>
        <!-- Attack power -->
        <tr>
          <td><%= Current.character.min_attack %> - <%= Current.character.max_attack %></td>
          <td><p title="Min and Max Attack Power">ATK</p></td>
          <td><%= @monster.min_attack %> - <%= @monster.max_attack %></td>
        </tr>
        <!-- Defense rate -->
        <tr>
          <td><%= Current.character.defense_rate %></td>
          <td><p title="Defense Success Rate">DSR</p></td>
          <td><%= @monster.defense_rate %></td>
        </tr>
        <!-- Defense -->
        <tr>
          <td><%= Current.character.defense %></td>
          <td><p title="Defense">DEF</p></td>
          <td><%= @monster.defense %></td>
        </tr>
        <!-- Health -->
        <tr>
          <td><%= Current.character.max_health %></td>
          <td><p title="Health Points">HP</p></td>
          <td><%= @monster.health %></td>
        </tr>
      </table>

      <%= form_with url: combat_path, method: :post do |form| %>
        <%= hidden_field_tag :character_id, @monster.id %>
        <%= form.submit "Attack" %>
      <% end %>
    </section>
  <% end %>

  <ul class="menu">
    <li class="menu-item">
      <%= link_to "Try another", hunting_path %>
    </li>
    <li class="menu-item">
      <%= link_to "Hunting", hunting_index_path %>
    </li>
  </ul>
</article>