config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker.js" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "starts#show"

  resource :start, only: [ :show, :new, :create ]
  resource :session, only: [ :new, :create, :destroy ]
  resource :registration, only: [ :new, :create ]
  resources :password_resets, only: [ :new, :create ]
  resources :password_resets, param: :token, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]
  resource :settings, only: [ :show ]
  resources :characters do
    post "activate", on: :member
  end

  # Add stats
  post "add_strength", to: "add_stats#strength"
  post "add_agility", to: "add_stats#agility"
  post "add_vitality", to: "add_stats#vitality"
  post "add_energy", to: "add_stats#energy"

  # Adventure (walk without teleport)
  resource :adventure, only: [ :show ] do
    post "travel"
  end

  resources :hunting, only: [ :index, :show ]
  resource :combat, only: [ :new, :create, :show ]
end

app/models/characters/character.rb
module Characters
  # Base class for all character types. Do not use directly.
  class Character < ApplicationRecord
    belongs_to :map
    belongs_to :location, optional: true

    validates :map, presence: true
    validates :name, presence: true, uniqueness: true, length: { in: 4..20 }

    def attacks
      1
    end

    def dead?
      health <= 0
    end
  end
end

app/models/characters/dark_knight.rb
module Characters
  class DarkKnight < Player
    def self.order
      1
    end

    def has_wizardy?
      false
    end

    def calculate_attack_rate
      (level * 5 + agility * 1.5 + strength / 4).floor
    end

    def calculate_min_attack
      (strength / 6).floor
    end

    def calculate_max_attack
      (strength / 4).floor
    end

    def calculate_defense
      (agility / 3).floor
    end

    def calculate_defense_rate
      (agility / 3).floor
    end

    def calculate_health
      35 + (level - 1) + vitality * 3
    end

    def calculate_health_regen
      1 + (vitality / 20).floor + (0.015 * max_health).floor
    end

    def calculate_mana
      10 + ((level - 1) / 2).floor + energy
    end

    def calculate_mana_regen
      1 + (calculate_mana / 27.5).floor
    end

    private

    def set_default_stats!
      self.map = Map.first
      self.strength = 28
      self.agility = 20
      self.vitality = 25
      self.energy = 10
    end
  end
end

app/models/characters/dark_wizard.rb
module Characters
  class DarkWizard < Player
    def self.order
      2
    end

    def has_wizardy?
      true
    end

    def calculate_attack_rate
      (level * 5 + agility * 1.5 + energy / 4).floor
    end

    def calculate_min_attack
      (energy / 9).floor
    end

    def calculate_max_attack
      (energy / 4).floor
    end

    def calculate_defense
      (agility / 4).floor
    end

    def calculate_defense_rate
      (agility / 3).floor
    end

    def calculate_health
      30 + (level - 1) + vitality * 2
    end

    def calculate_health_regen
      1 + (vitality / 20).floor + (0.015 * max_health).floor
    end

    def calculate_mana
      (energy + level - 1) * 2
    end

    def calculate_mana_regen
      1 + (calculate_mana / 27.5).floor
    end

    private

    def set_default_stats!
      self.map = Map.first
      self.strength = 18
      self.agility = 18
      self.vitality = 15
      self.energy = 30
    end
  end
end

app/models/characters/elf.rb
module Characters
  class Elf < Character
    def self.order
      3
    end

    def has_wizardy?
      false
    end

    def calculate_attack_rate
      (level * 5 + agility * 1.5 + energy / 4).floor
    end

    def calculate_min_attack
      (strength + agility * 2).floor / 14
    end

    def calculate_max_attack
      (strength + agility * 2).floor / 8
    end

    def calculate_min_wizard
      0
    end

    def calculate_max_wizard
      0
    end

    def calculate_defense
      (agility / 10).floor
    end

    def calculate_defense_rate
      (agility / 4).floor
    end

    def calculate_health
      40 + (level - 1) + vitality * 2
    end

    def calculate_health_regen
      1 + (vitality / 20).floor + (0.015 * max_health).floor
    end

    def calculate_mana
      (6 + (energy + level) * 1.5).floor
    end

    def calculate_mana_regen
      1 + (calculate_mana / 27.5).floor
    end

    private

    def set_default_stats!
      self.profession = Profession.find_by(code: "fe")
      self.strength = 22
      self.agility = 25
      self.vitality = 20
      self.energy = 15
    end
  end
end

app/models/characters/fairy_elf.rb
module Characters
  class FairyElf < Player
    def self.order
      3
    end

    def has_wizardy?
      false
    end

    def calculate_attack_rate
      (level * 5 + agility * 1.5 + energy / 4).floor
    end

    def calculate_min_attack
      (strength + agility * 2).floor / 14
    end

    def calculate_max_attack
      (strength + agility * 2).floor / 8
    end

    def calculate_defense
      (agility / 10).floor
    end

    def calculate_defense_rate
      (agility / 4).floor
    end

    def calculate_health
      40 + (level - 1) + vitality * 2
    end

    def calculate_health_regen
      1 + (vitality / 20).floor + (0.015 * max_health).floor
    end

    def calculate_mana
      (6 + (energy + level) * 1.5).floor
    end

    def calculate_mana_regen
      1 + (calculate_mana / 27.5).floor
    end

    private

    def set_default_stats!
      self.map = Map.first
      self.strength = 22
      self.agility = 25
      self.vitality = 20
      self.energy = 15
    end
  end
end

app/models/characters/monster.rb
module Characters
  class Monster < Character
    validates :location, presence: true

    before_create :calculate_params

    def attacks
      1
    end

    def has_wizardy?
      false
    end

    def calculate_attack_rate
      (agility * 1.5).floor
    end

    def calculate_min_attack
      strength
    end

    def calculate_max_attack
      strength * 2
    end

    def calculate_defense
      (agility / 5).floor
    end

    def calculate_defense_rate
      (agility / 5).floor
    end

    def calculate_health
      vitality * 5
    end

    def calculate_health_regen
      1
    end

    def calculate_mana
      energy * 10
    end

    def calculate_mana_regen
      1
    end

    def calculate_params
      self.attack_rate = calculate_attack_rate
      self.min_attack = calculate_min_attack
      self.max_attack = calculate_max_attack
      self.defense_rate = calculate_defense_rate
      self.defense = calculate_defense
      self.max_health = calculate_health
      self.max_mana = calculate_mana
      self.health = max_health
      self.mana = max_mana
    end
  end
end

app/models/characters/player.rb
module Characters
  class Player < Character
    before_validation :abort_if_invalid_type
    before_validation :calculate_params!, if: :new_record?

    belongs_to :user
    has_many :game_logs, class_name: "GameLogs::GameLog", foreign_key: "character_id", dependent: :destroy

    validates :user, presence: true

    def attacks
      2
    end

    def profession
      type.split("::").last # Get last part (e.g., "DarkKnight")
          .underscore       # Convert "DarkKnight" -> "dark_knight"
          .humanize         # Convert "dark_knight" -> "Dark Knight"
    end

    def restore
      return unless can_restore?

      self.update(last_restore_at: Time.current, activity: 100)
    end

    def regenerate
      CharacterRegenerationService.call(self)
    end

    def add_experience(xp)
      remaining_xp = xp
      new_level = self.level
      new_experience = self.experience

      while remaining_xp > 0
        xp_needed = calculate_max_experience - new_experience

        if remaining_xp >= xp_needed
          new_level += 1
          remaining_xp -= xp_needed
          new_experience = 0
        else
          new_experience += remaining_xp
          remaining_xp = 0
        end
      end

      self.update!(level: new_level, experience: new_experience)
    end

    def add_gold(gold)
      self.update!(gold: self.gold + gold)
    end

    def self.order
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def has_wizardy?
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_attack_rate
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_min_attack
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_max_attack
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_min_wizard
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_max_wizard
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_defense
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_defense_rate
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_health
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_health_regen
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_mana
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_mana_regen
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_max_experience
      # 5 * level * level - 5 * level + 10
      10
    end

    private

    def abort_if_invalid_type
      unless Characters::PlayerRegistry.all.values.include?(self[:type])
        errors.add(:type, I18n.t("errors.invalid_character_type", default: "is not a valid character type"))
        throw(:abort)
      end
    end

    def set_default_stats!
      raise NotImplementedError, "You must implement the method in Player subclass"
    end

    def calculate_params!
      set_default_stats!
      self.max_experience = calculate_max_experience
      self.attack_rate = calculate_attack_rate
      self.min_attack = calculate_min_attack
      self.max_attack = calculate_max_attack
      self.defense_rate = calculate_defense_rate
      self.defense = calculate_defense
      self.max_health = calculate_health
      self.max_mana = calculate_mana
      self.health = max_health
      self.mana = max_mana
    end

    def can_restore?
      last_restore_at < 1.minutes.ago
    end
  end
end

app/models/characters/player_registry.rb
module Characters
  class PlayerRegistry
    MAPPING = {
      "darkknight" => "Characters::DarkKnight",
      "darkwizard" => "Characters::DarkWizard",
      "fairyelf" => "Characters::FairyElf"
    }.freeze

    REVERSE_MAPPING = MAPPING.invert.freeze

    def self.all
      MAPPING
    end

    def self.valid_keys
      MAPPING.keys
    end

    def self.class_name_for(key)
      MAPPING[key]
    end

    def self.key_for_class(class_name)
      REVERSE_MAPPING[class_name]
    end

    def self.options_for_select
      MAPPING.map { |key, class_name| [ human_name_for(key), key ] }
    end

    def self.human_name_for(input)
      key =
        if valid_keys.include?(input)
          input
        elsif key = key_for_class(input)
          key
        else
          nil
        end

      key = input unless key

      I18n.t("characters.#{key}")
    end

    def self.human_name_for(key)
      I18n.t("characters.#{key}")
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  allow_unactivated_character_access

  def index
    @characters = Current.user.characters
  end

  def show
    begin
      @character = Current.user.characters.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to characters_path, alert: "Character not found."
    end
  end

  def new
    @character = Characters::Character.new
  end

  def create
    ctype = Characters::PlayerRegistry.class_name_for(character_params[:type])
    character_creator_service = CharacterCreatorService.new(
      user: Current.user,
      name: character_params[:name],
      type: ctype
    )

    @character = character_creator_service.call

    if @character.persisted?
      redirect_to characters_path, notice: "Character created successfully."
    else
      flash.now[:alert] = "Failed to create character."
      render :new, status: :unprocessable_entity
    end
  end

  def activate
    Rails.logger.info(Current.user.inspect)
    if character = Current.user.characters.find(params[:id])
      flash[:notice] = "Character #{character.name} has been activated."
      # update_attribute - skip password validation that is in standard update
      Current.user.update_attribute(:character, character)
    end

    redirect_to characters_path
  end

  private

  def character_params
    params.require(:characters_character).permit(:name, :type)
  end
end

app/views/characters/index.html.erb
<article>
  <h1>My characters</h1>

  <section class="action-block">
    <div class="action-descriptions">
      <p>You can create new character or choose character to play with.</p>
    </div>
    <%= link_to "New character", new_character_path, class: "action-button" %>
  </section>
  
  <article style="padding: 0px 6px;">
    <% @characters.each do |character| %>
      <section>
        <%= link_to character_path(character) do %>
          <h2>
            <%= character.name %>
            <% if character == Current.character %>
              <sup>*</sup>
            <% end %>
          </h2>
        <% end %>

        <p>
          <%= character.profession %> <strong>[<%= character.level %>]</strong>
        </p>
        
        <% if character != Current.character %>
          <%= button_to "Activate", activate_character_path(character), method: :post, class: "action-button" %>
        <% end %>
      </section>
    <% end %>
  </article>
</article>

app/views/characters/new.html.erb
<article>
  <h1>Create character</h1>

  <%= form_with model: @character, url: characters_path do |form| %>
    <% if @character.errors.any? %>
      <div class="error_messages">
        <h2>Errors:</h2>
        <ul>
          <% @character.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :type %>
      <%= form.select :type, Characters::Player.character_types %>
    </div>

    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit "Create" %>
    </div>
  <% end %>
</article>

app/views/characters/show.html.erb
<article>
  <% image_tag "469x469_dark_wizard.png", alt: "Dark Wizard portret" %>
  
  <h3>Character</h3>
  <table>
    <tbody>
      <tr>
        <td colspan="2"></td>
        <td>Name</td>
        <td><%= @character.name %></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Class</td>
        <td><%= @character.profession %></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Experience</td>
        <td>
          <%= (@character.experience.to_f / @character.max_experience * 100).floor %>%
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Level</td>
        <td><%= @character.level %></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Points</td>
        <td><%= @character.points %></td>
      </tr>
    </tbody>
  </table>

  <h3>Attributes</h3>
  <table>
    <tbody>
      <!-- Strength -->
      <tr>
        <td colspan="2"><strong>Strength</strong></td>
        <td></td>
        <td style="display: flex; gap: 5px">
          <strong><%= @character.strength %></strong>
          <% unless @character.points.zero? %>
            <%= button_to '+', add_strength_path, method: :post %>
          <% end %>
        </td>
      </tr>
      <% unless @character.has_wizardy? %>
      <tr>
        <td colspan="2"></td>
        <td>Attack</td>
        <td>
          <%= @character.min_attack %>
          &mdash;
          <%= @character.max_attack %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Attack rate</td>
        <td><%= @character.attack_rate %></td>
      </tr>
      <% end %>

      <!-- Agility -->
      <tr>
        <td colspan="2"><strong>Agility</strong></td>
        <td></td>
        <td style="display: flex; gap: 5px">
          <strong><%= @character.agility %></strong>
          <% unless @character.points.zero? %>
            <%= button_to '+', add_agility_path, method: :post %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Defense</td>
        <td><%= @character.defense %></td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Defense rate</td>
        <td><%= @character.defense_rate %></td>
      </tr>

      <!-- Vitality -->
      <tr>
        <td colspan="2"><strong>Vitality</strong></td>
        <td></td>
        <td style="display: flex; gap: 5px">
          <strong><%= @character.vitality %></strong>
          <% unless @character.points.zero? %>
            <%= button_to '+', add_vitality_path, method: :post %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Health</td>
        <td><%= @character.max_health %></td>
      </tr>

      <!-- Energy -->
      <tr>
        <td colspan="2"><strong>Energy</strong></td>
        <td></td>
        <td style="display: flex; gap: 5px">
          <strong><%= @character.energy %></strong>
          <% unless @character.points.zero? %>
            <%= button_to '+', add_energy_path, method: :post %>
          <% end %>
        </td>
      </tr>
      <% if @character.has_wizardy? %>
      <tr>
        <td colspan="2"></td>
        <td>Attack</td>
        <td>
          <%= @character.min_attack %>
          &mdash;
          <%= @character.max_attack %>
        </td>
      </tr>
      <tr>
        <td colspan="2"></td>
        <td>Attack rate</td>
        <td><%= @character.attack_rate %></td>
      </tr>
      <% end %>
      <tr>
        <td colspan="2"></td>
        <td>Mana</td>
        <td><%= @character.mana %></td>
      </tr>
    </tbody>
  </table>
</article>