config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker.js" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "starts#show"

  resource :start, only: [ :show, :new, :create ]
  resource :session, only: [ :new, :create, :destroy ]
  resource :registration, only: [ :new, :create ]
  resources :password_resets, only: [ :new, :create ]
  resources :password_resets, param: :token, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]
  resource :settings, only: [ :show ]
  resources :characters do
    post "activate", on: :member
  end

  # Add stats
  post "add_strength", to: "add_stats#strength"
  post "add_agility", to: "add_stats#agility"
  post "add_vitality", to: "add_stats#vitality"
  post "add_energy", to: "add_stats#energy"

  # Adventure (walk without teleport)
  resource :adventure, only: [ :show ] do
    post "travel"
  end

  resources :hunting, only: [ :index, :show ]
  resource :combat, only: [ :new, :create, :show ]
end

app/controllers/starts_controller.rb
class StartsController < ApplicationController
  disallow_authenticated_access
  allow_unauthenticated_access
  allow_unactivated_character_access

  def new
    @character = Characters::Player.new
  end

  def create
    ActiveRecord::Base.transaction do
      user = UserCreatorService.new.call
      ctype = Characters::PlayerRegistry.class_name_for(character_params[:type])
      @character = CharacterCreatorService.new(
        user: user,
        name: character_params[:name],
        type: ctype
      ).call

      unless @character.valid? && @character.persisted?
        raise ActiveRecord::Rollback
      end

      start_new_session_for user
      redirect_to adventure_path and return
    end

    render :new, status: :unprocessable_entity
  end

  def show
  end

  private

  def character_params
    params.require(:characters_character).permit(:name, :type)
  end
end

app/views/starts/new.html.erb
<article>
  <h1>Create character</h1>

  <%= form_with model: @character, url: start_path, method: :post, scope: :characters_character do |form| %>
    <% if @character.errors.any? %>
      <div class="error_messages">
        <h2>Errors:</h2>
        <ul>
          <% @character.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :type %>
      <%= form.select :type, Characters::PlayerRegistry.options_for_select %>
    </div>

    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.submit "Play" %>
    </div>
  <% end %>
</article>

app/views/starts/show.html.erb
<%= image_tag("start.png", alt: "Landing welcome image", class:"start-image") %>

<section class="action-block">
  <div class="action-descriptions">
    <p>New mmorpg fantasy game - Cloud MU Online!</p>
    <p>Adventures, Battles, enemies and friends, all from your browser!</p>
    <p>Level up your character your way!</p>
  </div>
  <%= link_to "Start new game", new_start_path, class: "action-button" %>
</section>

<div class="hr"></div>
<ul class="menu player-menu">
  <li class="menu-item"><%= link_to "Log in", new_session_path %></li>
</ul>
<div class="hr"></div>