config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount MissionControl::Jobs::Engine, at: "/jobs"

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker.js" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "starts#show"

  resource :start, only: [ :show, :new, :create ]
  resource :session, only: [ :new, :create, :destroy ]
  resource :registration, only: [ :new, :create ]
  resources :password_resets, only: [ :new, :create ]
  resources :password_resets, param: :token, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]
  resource :settings, only: [ :show ]
  resources :characters do
    post "activate", on: :member
  end

  # Add stats
  post "add_strength", to: "add_stats#strength"
  post "add_agility", to: "add_stats#agility"
  post "add_vitality", to: "add_stats#vitality"
  post "add_energy", to: "add_stats#energy"

  # Adventure (walk without teleport)
  resource :adventure, only: [ :show ] do
    post "travel"
  end

  resources :hunting, only: [ :index, :show ]
  resource :combat, only: [ :new, :create, :show ]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="Author" content="Vyacheslav Odinokov">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>Cloud MU Online</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "icons", "layout", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <article class="root">
      <main>
        <header>
          <%= link_to root_path, title: "To main page", class: "w-full" do %>
            <h1>Cloud MU Online</h1>
          <% end %>
        </header>

        <% if Current.user&.is_guest %>
          <article class="complete-register">
            <%= link_to new_registration_path, title: "Complete registration" do %>
              <p>Register your account and get rewards</p>
            <% end %>
          </article>
        <% end %>
        
        <% if authenticated? %>
          <section class="player-status">
            <% if Current.character&.persisted? %>
              <div class="player-info">
                <p>
                  <span class="icon dark-wizard-icon"></span>
                  <%= Current.character.name %>
                </p>

                <p>
                  <span class="icon health-icon"></span>
                  <%= Current.character.health %> / <%= Current.character.max_health %>
                </p>
                <p>
                  <span class="icon mana-icon"></span>
                  <%= Current.character.mana %> / <%= Current.character.max_mana %>
                </p>
                <p>
                  <span class="icon activity-icon"></span>
                  <%= Current.character.activity %>
                </p>

                <p>
                  <span class="icon gold-coin-icon"></span>
                  0
                </p>
              </div>
            <% end %>
          </section>
        <% end %>

        <% if notice or alert %>
          <article class="notification">
            <% if notice %>
              <p><%= notice %></p>
            <% end %>
            <% if alert %>
              <p><%= alert %></p>
            <% end %>
          </article>
        <% end %>

        <%= yield %>

        <% if authenticated? %>
          <section class="">
            <div class="hr"></div>
            <div class="hr"></div>
              <ul class="menu player-menu">
                <% if Current.character&.persisted? %>
                  <li class="menu-item"><%= link_to "Adventure", adventure_path %></li>
                  <li class="menu-item"><%= link_to "Character", character_path(Current.character) %></li>
                <% end %>
                <li class="menu-item"><%= link_to "Settings", settings_path %></li>
                <li class="menu-item"><%= button_to "Logout", session_path, method: :delete %></li>
              </ul>
            <div class="hr"></div>
            <div class="hr"></div>
          <section>
        <% end %>
      </main>
      <footer>
        <small>&copy; 2024 Vyacheslav Odinokov. All rights reserved.</small>
      </footer>
    </article>
  </body>
</html>